### ISSUE TITLE
Create & Manage High-level Project Plan

### ISSUE THREAD

**Issue by aukgit** [aukgit/alimkarim.com#1]
### Stage 1: Planning, Analysis
- [x] Create high-level features list in xmind.
- [x] Create breakdowns of each feature elements in xmind.
- [x] Create probable relationships with each element.

### Stage 2: Requirements Analysis
- [ ] Write feasibility analysis (including schedule/time,cost/budget, technical-{technologies,UI,platforms and communication among platforms}, outcome)
- [ ] Write Project Requirements from the breakdown of the feature and its relationship
- [ ] Re-modify breakdowns and it's relationships for Revision-2.
- [ ] Re-write Project Requirements from the updated breakdown of the feature and its relationship from Revision-2.
- [ ] Re-modify breakdowns and it's relationships for Revision-3.
- [ ] Re-write Project Requirements from the updated breakdown of the feature and its relationship with Revision-3.
- [ ] Possible finalization of the breakdowns. Revision-1
- [ ] Possible finalization of Project Requirements from the possible finalized breakdown of the feature and its relationship. Revision-1
- [ ] Write possible pages names.
- [ ] Create UI prototypes using Pencil UI tool.

### Stage 3: System Designing
- [ ] Design a draft database based on the requirements gathered.
- [ ] Revise Database design based on additional changes. Revision-2
- [ ] Revise Database design based on additional changes. Revision-3
- [ ] Structure the project based on the architecture that we want to implement.
- [ ] Identify exposing APIs.
- [ ] Draft API security measures.
- [ ] Identify integration techniques with Linkedin, facebook, google+ using OAuth.
- [ ] Presentation Layer - Gather possible UI usages, point and note those down. Plus, modification steps need to be identified.
- [ ] Presentation Layer + UI Business Logic - Configure a JavaScript framework to organize client-side codes.

### Stage 4: System Building
- [ ] Data Access Layer  - Create data access layer as per the designed database.
- [ ] Business Logic Layer - Implement features based on requirements gathered.
- [ ] Business Logic - Implement and expose APIs features based on requirements gathered.
- [ ] Business Logic - Secure APIs.
- [ ] Business Logic - Integrate third party API from Linkedin.
- [ ] Business Logic - Integrate third party API from Facebook.
- [ ] Business Logic - Integrate third party API from GooglePlus.
- [ ] Presentation Layer - Develop presentation UI based on identified components.
- [ ] Presentation Layer - Develop presentation UI based on identified components.
- [ ] Presentation Layer - Customize and modify UI components to as per the business requirements.
- [ ] TODO - Write Unit test as we progress.
- [ ] Create and configure our deployment scripts.

### Stage 5: Integration and Testing (Test Environment)
- [ ] Use the deployment procedure and scripts to deploy the project in our test environment and test the project.

### Stage 6: Production (Deployment at alimkarim.com)
- [ ] Use the deployment procedure and scripts to deploy the project in production

### Stage 7: Operation and Maintenance 
- [ ] Create wiki details
- [ ] To be Continuted
